---
title: "GFRN Paper Supplemental Figure XX, EC50 Values for ICBP Drugs and Independent Assay Drugs"
author: "David Jenkins"
date: "January 23, 2017"
output:
  html_document:
    toc: true
    toc_float: true
    theme: "united"
---

```{r echo=FALSE, warning=FALSE, message=FALSE}
library(ggplot2)
library(gridExtra)
#install development version of ComplexHeatmap https://github.com/jokergoo/ComplexHeatmap
library(ComplexHeatmap)
library(data.table)
library(RColorBrewer)
library(cluster)

#-------------------------------------------------------------------------------
#Input files (Modify These to Your System's Locations):
#-------------------------------------------------------------------------------
input_data_dir <- file.path("/home","david","Dropbox","bild_signatures",
                           "david_results","final_pathway_predictions",
                           "20161214_reanalysis")
#the input should be scaled pathway prediction values, from AdditionalFile3
icbp_predictions_file <- file.path(input_data_dir,
                                   "optimized_single_pathway_icbp_scaled.txt")
#the input should be scaled pathway prediction values, from AdditionalFile3
tcga_predictions_file <- file.path(input_data_dir,
                                   "optimized_single_pathway_tcga_scaled.txt")
icbp_status_file <- file.path(input_data_dir,
                              "icbpstatus_v2.txt")
icbp_intrinsic_file <- file.path(input_data_dir,
                                 "intrinsic.txt")
tcga_status_rds_file <- file.path(input_data_dir,
                                  "tcga_er_pr_her2_formatted.rds")
tcga_intrinsic_file <- file.path(input_data_dir,
                                 "TCGA_single_pathway_best_phenotype_intrinsic.txt")
icbp_drugs_ec50_file <- file.path(input_data_dir, "ICBP_drugs.txt")
indepenent_assay_ec50_file <- file.path(input_data_dir, "Drug_response_assay.txt")

#-------------------------------------------------------------------------------
#Prepare TCGA Input:
#-------------------------------------------------------------------------------
#input tcga pathway data
single_pathway_best_tcga <-read.table(tcga_predictions_file, stringsAsFactors=FALSE,
                                      header=1, row.names=1,sep='\t')
#IHC Subtypes TCGA
er_pr_her2_status2 <- readRDS(tcga_status_rds_file)
#Intrinsic Subtypes TCGA
tcgaintrinsic <- read.table(tcga_intrinsic_file, 
                            row.names = 1, header=T, sep="\t")
tcgaintrinsic <- tcgaintrinsic[rownames(single_pathway_best_tcga),12,drop=F]
tcgaintrinsic$PAM50 <- as.character(tcgaintrinsic$PAM50)
rownames(tcgaintrinsic) <- rownames(single_pathway_best_tcga)
tcgaintrinsic$PAM50[is.na(tcgaintrinsic$PAM50)] <- "Unavailable"
tcgaintrinsic <- cbind(er_pr_her2_status2, tcgaintrinsic)
single_pathway_best_tcga <- cbind(single_pathway_best_tcga, tcgaintrinsic)
rm(er_pr_her2_status2, tcgaintrinsic)

#-------------------------------------------------------------------------------
#Prepare ICBP Input:
#-------------------------------------------------------------------------------
#input icbp pathway data
single_pathway_best_icbp <-read.table(icbp_predictions_file, stringsAsFactors=FALSE,
                                      header=1, row.names=1,sep='\t')
rownames(single_pathway_best_icbp)[50] <- "T47D.Kbluc"
#IHC Subtypes ICBP
icbp_status <- read.table(icbp_status_file, row.names = 1, header=T, sep="\t")
#Intrinsic Subtypes ICBP
intrinsic <- read.table(icbp_intrinsic_file, row.names = 1, header=T, sep="\t")
colnames(intrinsic) <- "Intrinsic.Subtype"
rownames(intrinsic)[50] <- "T47D.Kbluc"
intrinsic <- intrinsic[rownames(single_pathway_best_icbp),,drop=F]
intrinsic <- cbind(icbp_status, intrinsic)
single_pathway_best_icbp <- cbind(single_pathway_best_icbp, intrinsic)
rm(intrinsic, icbp_status)

#-------------------------------------------------------------------------------
#Prepare EC50 Inputs:
#-------------------------------------------------------------------------------
icbp_drugs_ec50 <- read.delim(icbp_drugs_ec50_file, header=1, sep='\t',row.names=1)
rownames(icbp_drugs_ec50)[52] <- "MDAMB175"
rownames(icbp_drugs_ec50)[38] <- "SUM1315"
rownames(icbp_drugs_ec50)[45] <- "T47D.Kbluc"

icbp_drugs_ec50 <- icbp_drugs_ec50[rownames(single_pathway_best_icbp),c("Cisplatin","Paclitaxel","CGC.11047","Docetaxel",
                                      "GSK1120212","Erlotinib","AZD6244","AG1478","Gefitinib",
                                      "Lapatinib","GSK1059615","GSK2119563","GSK2126458",
                                      "Temsirolimus","Sigma.AKT1.2.inhibitor","Rapamycin",
                                      "GSK1059868","Everolimus","GSK2141795","PF.4691502")]
icbp_status <- read.table(icbp_status_file, row.names = 1, header=T, sep="\t")
#Intrinsic Subtypes ICBP
intrinsic <- read.table(icbp_intrinsic_file, row.names = 1, header=T, sep="\t")
colnames(intrinsic) <- "Intrinsic.Subtype"
rownames(intrinsic)[50] <- "T47D.Kbluc"
intrinsic <- intrinsic[rownames(single_pathway_best_icbp),,drop=F]

intrinsic <- cbind(icbp_status, intrinsic)
icbp_drugs_ec50 <- cbind(icbp_drugs_ec50, single_pathway_best_icbp[,c("phenotype","kmeans.cluster")],intrinsic)
colnames(icbp_drugs_ec50)[21] <- "Phenotype"
rm(intrinsic, icbp_status)

indepenent_assay_ec50 <- read.delim(indepenent_assay_ec50_file, header=1, sep='\t',row.names=1)
icbp_status <- read.table(icbp_status_file, row.names = 1, header=T, sep="\t")
icbp_status <- icbp_status[rownames(indepenent_assay_ec50),,drop=F]
#Intrinsic Subtypes ICBP
intrinsic <- read.table(icbp_intrinsic_file, row.names = 1, header=T, sep="\t")
colnames(intrinsic) <- "Intrinsic.Subtype"
rownames(intrinsic)[50] <- "T47D.Kbluc"
intrinsic <- intrinsic[rownames(indepenent_assay_ec50),,drop=F]

intrinsic <- cbind(icbp_status, intrinsic)
indepenent_assay_ec50 <- cbind(indepenent_assay_ec50, single_pathway_best_icbp[rownames(indepenent_assay_ec50),c("phenotype","kmeans.cluster")],intrinsic)
colnames(indepenent_assay_ec50)[10] <- "Phenotype"
rm(intrinsic, icbp_status)
```

## (A): ICBP Drug Response, EC50

```{r echo=FALSE, warning=FALSE, message=FALSE, fig.width=7, fig.height=7}
create_ICBPdrug_response_ec50 <- function(expression_subtypes_df, showLegends=TRUE){
  set.seed(123)
  
  ha_row_icbp1 = HeatmapAnnotation(df = expression_subtypes_df[,c(21,23:26)],
                                   name="Intrinsic Subtype",
                                   col = list(Phenotype = c("Survival Phenotype" =  "coral3",
                                                            "Growth Phenotype" = "aquamarine4"),
                                              PR = c("Positive" =  "#4DAF4A",
                                                     "Negative" = "#984EA3",
                                                     "Unavailable" = "grey"),
                                              HER2 = c("Positive" =  "#FFFF33",
                                                       "Negative" = "#F781BF",
                                                       "Unavailable" = "grey"),
                                              ER = c("Positive" =  "#E41A1C",
                                                     "Negative" = "#377EB8",
                                                     "Unavailable" = "grey"),
                                              Intrinsic.Subtype = c("Basal" = '#e41a1c',
                                                                    "Claudin-low" = '#fccaa4',
                                                                    "HER2-Basal" = brewer.pal(6, "Dark2")[3],
                                                                    "HER2-Luminal" = brewer.pal(6, "Dark2")[4],
                                                                    "Luminal" = brewer.pal(6, "Dark2")[5],
                                                                    "Normal-like" = brewer.pal(6, "Dark2")[6],
                                                                    "Unavailable" = "grey")),
                                   which = "row",
                                   width = unit(1.667, "cm"),
                                   show_legend = showLegends)

  h1 <- Heatmap(scale(expression_subtypes_df[!(rownames(expression_subtypes_df) %in% c("21MT2", "EFM192C","HCC1599","HCC2218","MB157","21PT","ZR7530","BT483","HCC202","UACC893")),1:20]),
                cluster_rows = T,
                clustering_method_rows = "complete",
                clustering_distance_rows = function(x) daisy(x,metric="gower"),
                cluster_columns = F,
                show_row_names = T,
                show_column_names = T,
                row_title_gp = gpar(fontsize =10),
                combined_name_fun = NULL,
                name="Scaled\nEC50",
                column_title = "Original ICBP EC50",
                show_heatmap_legend = showLegends,
                row_names_side = "left",
                heatmap_legend_param = list(color_bar = "continuous"))

  draw(h1+ha_row_icbp1,row_dend_side = "left", annotation_legend_side = "bottom")
}

#uncomment to create PDF version of 2a
# pdf("Fig2a.pdf", width=6)
# create_figure2_a_TCGA_allpath(single_pathway_best_tcga, showLegends = F)
# dev.off()

create_ICBPdrug_response_ec50(icbp_drugs_ec50)
```

## (B): ICBP, all pathways

```{r echo=FALSE, warning=FALSE, message=FALSE, fig.width=7, fig.height=7}
create_independent_drug_response_ec50 <- function(expression_subtypes_df, showLegends=TRUE){
  set.seed(123)
  
  ha_row_icbp1 = HeatmapAnnotation(df = expression_subtypes_df[,c(10,12:15)],
                                   name="Intrinsic Subtype",
                                   col = list(Phenotype = c("Survival Phenotype" =  "coral3",
                                                            "Growth Phenotype" = "aquamarine4"),
                                              PR = c("Positive" =  "#4DAF4A",
                                                     "Negative" = "#984EA3",
                                                     "Unavailable" = "grey"),
                                              HER2 = c("Positive" =  "#FFFF33",
                                                       "Negative" = "#F781BF",
                                                       "Unavailable" = "grey"),
                                              ER = c("Positive" =  "#E41A1C",
                                                     "Negative" = "#377EB8",
                                                     "Unavailable" = "grey"),
                                              Intrinsic.Subtype = c("Basal" = '#e41a1c',
                                                                    "Claudin-low" = '#fccaa4',
                                                                    "HER2-Basal" = brewer.pal(6, "Dark2")[3],
                                                                    "HER2-Luminal" = brewer.pal(6, "Dark2")[4],
                                                                    "Luminal" = brewer.pal(6, "Dark2")[5],
                                                                    "Normal-like" = brewer.pal(6, "Dark2")[6],
                                                                    "Unavailable" = "grey")),
                                   which = "row",
                                   width = unit(1.667, "cm"),
                                   show_legend = showLegends)
  
  h1 <- Heatmap(scale(expression_subtypes_df[,1:9]),
                cluster_rows = T,
                #clustering_method_rows = "complete",
                #clustering_distance_rows = function(x) daisy(x,metric="gower"),
                cluster_columns = T,
                show_row_names = T,
                show_column_names = T,
                row_title_gp = gpar(fontsize =10),
                combined_name_fun = NULL,
                name="Scaled\nEC50",
                column_title = "Independent Assay EC50",
                show_heatmap_legend = showLegends,
                row_names_side = "left",
                heatmap_legend_param = list(color_bar = "continuous"))

  draw(h1+ha_row_icbp1,row_dend_side = "left", annotation_legend_side = "bottom")
}

#uncomment to create PDF version of 2a
# pdf("Fig2a.pdf", width=6)
# create_figure2_a_TCGA_allpath(single_pathway_best_tcga, showLegends = F)
# dev.off()

create_independent_drug_response_ec50(indepenent_assay_ec50)
```