---
title: "GFRN Paper Figure 2"
author: "David Jenkins"
date: "Dec 16, 2016"
output:
  html_document:
    toc: true
    toc_float: true
    theme: "united"
---

```{r echo=FALSE, warning=FALSE, message=FALSE}
library(ggplot2)
library(gridExtra)
#install development version of ComplexHeatmap https://github.com/jokergoo/ComplexHeatmap
library(ComplexHeatmap)
library(data.table)
library(RColorBrewer)
library(cluster)

#-------------------------------------------------------------------------------
#Input files (Modify These to Your System's Locations):
#-------------------------------------------------------------------------------
input_data_dir <- file.path("/home","david","Dropbox","bild_signatures",
                           "david_results","final_pathway_predictions",
                           "20161214_reanalysis")
#the input should be scaled pathway prediction values, from AdditionalFile3
icbp_predictions_file <- file.path(input_data_dir,
                                   "optimized_single_pathway_icbp_scaled.txt")
#the input should be scaled pathway prediction values, from AdditionalFile3
tcga_predictions_file <- file.path(input_data_dir,
                                   "optimized_single_pathway_tcga_scaled.txt")
icbp_status_file <- file.path(input_data_dir,
                              "icbpstatus_v2.txt")
icbp_intrinsic_file <- file.path(input_data_dir,
                                 "intrinsic.txt")
tcga_status_rds_file <- file.path(input_data_dir,
                                  "tcga_er_pr_her2_formatted.rds")
tcga_intrinsic_file <- file.path(input_data_dir,
                                 "TCGA_single_pathway_best_phenotype_intrinsic.txt")

#-------------------------------------------------------------------------------
#Prepare TCGA Input:
#-------------------------------------------------------------------------------
#input tcga pathway data
single_pathway_best_tcga <-read.table(tcga_predictions_file, stringsAsFactors=FALSE,
                                      header=1, row.names=1,sep='\t')
#IHC Subtypes TCGA
er_pr_her2_status2 <- readRDS(tcga_status_rds_file)
#Intrinsic Subtypes TCGA
tcgaintrinsic <- read.table(tcga_intrinsic_file, 
                            row.names = 1, header=T, sep="\t")
tcgaintrinsic <- tcgaintrinsic[rownames(single_pathway_best_tcga),12,drop=F]
tcgaintrinsic$PAM50 <- as.character(tcgaintrinsic$PAM50)
rownames(tcgaintrinsic) <- rownames(single_pathway_best_tcga)
tcgaintrinsic$PAM50[is.na(tcgaintrinsic$PAM50)] <- "Unavailable"
tcgaintrinsic <- cbind(er_pr_her2_status2, tcgaintrinsic)
single_pathway_best_tcga <- cbind(single_pathway_best_tcga, tcgaintrinsic)
rm(er_pr_her2_status2, tcgaintrinsic)

#-------------------------------------------------------------------------------
#Prepare ICBP Input:
#-------------------------------------------------------------------------------
#input icbp pathway data
single_pathway_best_icbp <-read.table(icbp_predictions_file, stringsAsFactors=FALSE,
                                      header=1, row.names=1,sep='\t')
rownames(single_pathway_best_icbp)[50] <- "T47D.Kbluc"
#IHC Subtypes ICBP
icbp_status <- read.table(icbp_status_file, row.names = 1, header=T, sep="\t")
#Intrinsic Subtypes ICBP
intrinsic <- read.table(icbp_intrinsic_file, row.names = 1, header=T, sep="\t")
colnames(intrinsic) <- "Intrinsic.Subtype"
rownames(intrinsic)[50] <- "T47D.Kbluc"
intrinsic <- intrinsic[rownames(single_pathway_best_icbp),,drop=F]
intrinsic <- cbind(icbp_status, intrinsic)
single_pathway_best_icbp <- cbind(single_pathway_best_icbp, intrinsic)
rm(intrinsic, icbp_status)
```

## (A): TCGA, all pathways

```{r echo=FALSE, warning=FALSE, message=FALSE, fig.width=7, fig.height=7}
create_figure2_a_TCGA_allpath <- function(expression_subtypes_df, showLegends=TRUE, ersubset="Full"){
  set.seed(123)
  phenotype.annotation <- data.frame(Phenotype=c("Survival Phenotype",
                                                 "Growth Phenotype",
                                                 "Growth Phenotype",
                                                 "Survival Phenotype",
                                                 "Survival Phenotype",
                                                 "Growth Phenotype",
                                                 "Growth Phenotype"))
  topha <- HeatmapAnnotation(df = phenotype.annotation,
                             col = list(Phenotype = c("Survival Phenotype" =  "coral3",
                                                      "Growth Phenotype" = "aquamarine4")),
                             height = unit(0.333, "cm"))
  maintitle <- "TCGA BRCA"
  if(ersubset != "Full"){
    expression_subtypes_df <- expression_subtypes_df[expression_subtypes_df$ER.Status == ersubset,]
    maintitle <- paste(maintitle,ersubset, sep=", ER ")
  }

  ha_row_tcga2 = HeatmapAnnotation(df = expression_subtypes_df[,10:13],
                                   col = list(PR.Status =   c("Positive" =  "#4DAF4A",
                                                              "Negative" = "#984EA3",
                                                              "Indeterminate" = "black",
                                                              "Unavailable" = "grey"),
                                              HER2.Status = c("Positive" =  "#FFFF33",
                                                              "Negative" = "#F781BF",
                                                              "Indeterminate" = "black",
                                                              "Equivocal" = "skyblue",
                                                              "Unavailable" = "grey"),
                                              ER.Status =   c("Positive" =  "#E41A1C",
                                                              "Negative" = "#377EB8",
                                                              "Indeterminate" = "black",
                                                              "Unavailable" = "grey"),
                                              PAM50 =       c("LumA" = brewer.pal(6, "Dark2")[5],
                                                              "LumB" = '#fccaa4',
                                                              "Her2" = brewer.pal(6, "Dark2")[4],
                                                              "Basal" = '#e41a1c',
                                                              "Normal" = brewer.pal(6, "Dark2")[6],
                                                              "Unavailable"="grey")),
                                   which = "row",
                                   width = unit(1.333, "cm"),
                                   show_legend = showLegends)
  h1 <- Heatmap(expression_subtypes_df[,1:7],
                cluster_rows = T,
                cluster_columns = T,
                show_row_names = F,
                show_column_names = T,
                row_title_gp = gpar(fontsize =10),
                combined_name_fun = NULL,
                top_annotation = topha,
                name="Scaled\nPathway\nActivity",
                column_title = maintitle,
                show_heatmap_legend = showLegends,
                column_dend_reorder = c(1,100,100,10,1,100,100),
                heatmap_legend_param = list(color_bar = "continuous"))
  draw(h1+ha_row_tcga2,row_dend_side = "left", annotation_legend_side = "bottom")
}

#uncomment to create PDF version of 2a
# pdf("Fig2a.pdf", width=6)
# create_figure2_a_TCGA_allpath(single_pathway_best_tcga, showLegends = F)
# dev.off()

create_figure2_a_TCGA_allpath(single_pathway_best_tcga)
```

## (B): ICBP, all pathways

```{r echo=FALSE, warning=FALSE, message=FALSE, fig.width=7, fig.height=7}
create_figure2_b_ICBP_allpath <- function(expression_subtypes_df, showLegends=TRUE, ersubset="Full"){
  set.seed(123)
  phenotype.annotation <- data.frame(Phenotype=c("Survival Phenotype",
                                                 "Growth Phenotype",
                                                 "Growth Phenotype",
                                                 "Survival Phenotype",
                                                 "Survival Phenotype",
                                                 "Growth Phenotype",
                                                 "Growth Phenotype"))
  topha <- HeatmapAnnotation(df = phenotype.annotation,
                             col = list(Phenotype = c("Survival Phenotype" =  "coral3",
                                                      "Growth Phenotype" = "aquamarine4")),
                             height = unit(0.333, "cm"))
  
  maintitle <- "ICBP"
  if(ersubset != "Full"){
    expression_subtypes_df <- expression_subtypes_df[expression_subtypes_df$ER == ersubset,]
    maintitle <- paste(maintitle,ersubset, sep=", ER ")
  }

  ha_row_icbp1 = HeatmapAnnotation(df = expression_subtypes_df[,10:13],
                                   name="Intrinsic Subtype",
                                   col = list(PR = c("Positive" =  "#4DAF4A",
                                                     "Negative" = "#984EA3",
                                                     "Unavailable" = "grey"),
                                              HER2 = c("Positive" =  "#FFFF33",
                                                       "Negative" = "#F781BF",
                                                       "Unavailable" = "grey"),
                                              ER = c("Positive" =  "#E41A1C",
                                                     "Negative" = "#377EB8",
                                                     "Unavailable" = "grey"),
                                              Intrinsic.Subtype = c("Basal" = '#e41a1c',
                                                                    "Claudin-low" = '#fccaa4',
                                                                    "HER2-Basal" = brewer.pal(6, "Dark2")[3],
                                                                    "HER2-Luminal" = brewer.pal(6, "Dark2")[4],
                                                                    "Luminal" = brewer.pal(6, "Dark2")[5],
                                                                    "Normal-like" = brewer.pal(6, "Dark2")[6],
                                                                    "Unavailable" = "grey")),
                                   which = "row",
                                   width = unit(1.333, "cm"),
                                   show_legend = showLegends)

  h1 <- Heatmap(expression_subtypes_df[,1:7],
                cluster_rows = T,
                cluster_columns = T,
                show_row_names = F,
                show_column_names = T,
                row_title_gp = gpar(fontsize =10),
                combined_name_fun = NULL,
                name="Scaled\nPathway\nActivity",
                top_annotation = topha,
                column_title = maintitle,
                show_heatmap_legend = showLegends,
                column_dend_reorder = c(1,100,100,10,1,100,100),
                heatmap_legend_param = list(color_bar = "continuous"))

  draw(h1+ha_row_icbp1,row_dend_side = "left", annotation_legend_side = "bottom")
}

#uncomment to create PDF version of 2b
# pdf("Fig2b.pdf", width=6)
# create_figure2_b_ICBP_allpath(single_pathway_best_icbp, showLegends = F)
# dev.off()

create_figure2_b_ICBP_allpath(single_pathway_best_icbp)
```

## (C): TCGA, k-means of 4 pathways

```{r echo=FALSE, warning=FALSE, message=FALSE, fig.width=7, fig.height=7}
#This is the code used to create the kmeans clusters. These values aren't used
#in the heatmap. Instead, the values inside AdditionalFile3 are used, but they
#are equivalent.
set.seed(123)
kmeans.4 <- kmeans(single_pathway_best_tcga[,c(1,2,3,4)], 4, iter.max=10000, nstart = 1000)
kmeans.4.clusters.tcga <-data.frame(kmeans.4$cluster)
kmeans.4.clusters.tcga[kmeans.4.clusters.tcga$kmeans.4.cluster == "3",] <- "Survival/HER2 high"
kmeans.4.clusters.tcga[kmeans.4.clusters.tcga$kmeans.4.cluster == "1",] <- "Survival/HER2 low"
kmeans.4.clusters.tcga[kmeans.4.clusters.tcga$kmeans.4.cluster == "2",] <- "Growth/BAD low"
kmeans.4.clusters.tcga[kmeans.4.clusters.tcga$kmeans.4.cluster == "4",] <- "Growth/BAD high"
rm(kmeans.4.clusters.tcga, kmeans.4)

create_figure2_c_TCGA_kmeans <- function(expression_subtypes_df, showLegends=TRUE){
  set.seed(123)
  phenotype.annotation <- data.frame(Phenotype=c("Survival Phenotype",
                                                 "Growth Phenotype",
                                                 "Growth Phenotype",
                                                 "Survival Phenotype",
                                                 "Survival Phenotype",
                                                 "Growth Phenotype",
                                                 "Growth Phenotype"))
  topha <- HeatmapAnnotation(df = phenotype.annotation,
                             col = list(Phenotype = c("Survival Phenotype" =  "coral3",
                                                      "Growth Phenotype" = "aquamarine4")),
                             height = unit(0.333, "cm"))
  
  kmeans.4.clusters.tcga <- expression_subtypes_df[,"kmeans.cluster",drop=F]
  colnames(kmeans.4.clusters.tcga) <- "KMeans.Clusters"
  ha_row_tcga = HeatmapAnnotation(df = kmeans.4.clusters.tcga,
                                  col = list(KMeans.Clusters = c("Survival/HER2 high" = brewer.pal(5, "Set1")[1],
                                                                 "Survival/HER2 low" = brewer.pal(5, "Set1")[2],
                                                                 "Growth/BAD high" = brewer.pal(5, "Set1")[3],
                                                                 "Growth/BAD low" = brewer.pal(5, "Set1")[5])),
                                  which = "row",
                                  width = unit(0.333, "cm"),
                                  show_legend = showLegends)

  ha_row_tcga2 = HeatmapAnnotation(df = expression_subtypes_df[,10:13],
                                   col = list(PR.Status = c("Positive" =  "#4DAF4A",
                                                            "Negative" = "#984EA3",
                                                            "Indeterminate" = "black",
                                                            "Unavailable" = "grey"),
                                              HER2.Status = c("Positive" =  "#FFFF33",
                                                              "Negative" = "#F781BF",
                                                              "Indeterminate" = "black",
                                                              "Equivocal" = "skyblue",
                                                              "Unavailable" = "grey"),
                                              ER.Status = c("Positive" =  "#E41A1C",
                                                            "Negative" = "#377EB8",
                                                            "Indeterminate" = "black",
                                                            "Unavailable" = "grey"),
                                              PAM50 = c("LumA" = brewer.pal(6, "Dark2")[5],
                                                        "LumB" = '#fccaa4',
                                                        "Her2" = brewer.pal(6, "Dark2")[4],
                                                        "Basal" = '#e41a1c',
                                                        "Normal" = brewer.pal(6, "Dark2")[6],
                                                        "Unavailable"="grey")),
                                   which = "row",
                                   width = unit(1.333, "cm"),
                                   show_legend = showLegends)

  h1 <- Heatmap(single_pathway_best_tcga[,c(1:4)],
                cluster_rows = T,
                cluster_columns = T,
                show_row_names = F,
                show_column_names = T,
                split=factor(kmeans.4.clusters.tcga$KMeans.Clusters,
                             levels=c("Survival/HER2 high",
                                      "Survival/HER2 low",
                                      "Growth/BAD high",
                                      "Growth/BAD low")),
                row_title_gp = gpar(fontsize =10),
                column_dend_reorder = c(1,4,100,2),
                combined_name_fun = NULL,
                top_annotation = topha,
                name="Scaled\nPathway\nActivity",
                column_title = "TCGA BRCA",
                show_heatmap_legend = showLegends,
                heatmap_legend_param = list(color_bar = "continuous"))
  draw(ha_row_tcga+h1+ha_row_tcga2,row_dend_side = "left", annotation_legend_side = "bottom")
}

#uncomment to create PDF version of 2c
# pdf("Fig2c.pdf", width=5.32)
# create_figure2_c_TCGA_kmeans(single_pathway_best_tcga, showLegends = F)
# dev.off()

create_figure2_c_TCGA_kmeans(single_pathway_best_tcga)
```

## (D): ICBP, k-means of 4 pathways

```{r echo=FALSE, warning=FALSE, message=FALSE, fig.width=7, fig.height=7}
#This is the code used to create the kmeans clusters. These values aren't used
#in the heatmap. Instead, the values inside AdditionalFile3 are used, but they
#are equivalent.
set.seed(123)
kmeans.4 <- kmeans(single_pathway_best_icbp[,c(1,2,3,4)], 4, iter.max=100000, nstart = 100)
kmeans.4.clusters <-data.frame(kmeans.4$cluster)
kmeans.4.clusters[kmeans.4.clusters$kmeans.4.cluster == "3",] <- "Survival/HER2 high"
kmeans.4.clusters[kmeans.4.clusters$kmeans.4.cluster == "1",] <- "Survival/HER2 low"
kmeans.4.clusters[kmeans.4.clusters$kmeans.4.cluster == "4",] <- "Growth/BAD high"
kmeans.4.clusters[kmeans.4.clusters$kmeans.4.cluster == "2",] <- "Growth/BAD low"
rm(kmeans.4, kmeans.4.clusters)

create_figure2_d_ICBP_kmeans <- function(expression_subtypes_df, showLegends=TRUE){
  set.seed(123)
  phenotype.annotation <- data.frame(Phenotype=c("Survival Phenotype",
                                                 "Growth Phenotype",
                                                 "Growth Phenotype",
                                                 "Survival Phenotype",
                                                 "Survival Phenotype",
                                                 "Growth Phenotype",
                                                 "Growth Phenotype"))
  topha <- HeatmapAnnotation(df = phenotype.annotation,
                             col = list(Phenotype = c("Survival Phenotype" =  "coral3",
                                                      "Growth Phenotype" = "aquamarine4")),
                             height = unit(0.333, "cm"))
  
  kmeans.4.clusters <- expression_subtypes_df[,"kmeans.cluster",drop=F]
  colnames(kmeans.4.clusters) <- "KMeans.Clusters"
  ha_row_icbp2 <- HeatmapAnnotation(df = kmeans.4.clusters,
                                    name="K-Means Clusters",
                                    col = list(KMeans.Clusters = c("Survival/HER2 high" = brewer.pal(5, "Set1")[1],
                                                                   "Survival/HER2 low" = brewer.pal(5, "Set1")[2],
                                                                   "Growth/BAD high" = brewer.pal(5, "Set1")[3],
                                                                   "Growth/BAD low" = brewer.pal(5, "Set1")[5])),
                                    which = "row",
                                    width = unit(0.333, "cm"),
                                    show_legend = showLegends)
  
  ha_row_icbp1 <- HeatmapAnnotation(df = expression_subtypes_df[,10:13],
                                    name="Intrinsic Subtype",
                                    col = list(PR = c("Positive" =  "#4DAF4A",
                                                      "Negative" = "#984EA3",
                                                      "Unavailable" = "grey"),
                                               HER2 = c("Positive" =  "#FFFF33",
                                                        "Negative" = "#F781BF",
                                                        "Unavailable" = "grey"),
                                               ER = c("Positive" =  "#E41A1C",
                                                      "Negative" = "#377EB8",
                                                      "Unavailable" = "grey"),
                                               Intrinsic.Subtype = c("Basal" = '#e41a1c',
                                                                     "Claudin-low" = '#fccaa4',
                                                                     "HER2-Basal" = brewer.pal(6, "Dark2")[3],
                                                                     "HER2-Luminal" = brewer.pal(6, "Dark2")[4],
                                                                     "Luminal" = brewer.pal(6, "Dark2")[5],
                                                                     "Normal-like" = brewer.pal(6, "Dark2")[6],
                                                                     "Unavailable" = "grey")),
                                    which = "row",
                                    width = unit(1.333, "cm"),
                                    show_legend = showLegends)

  h1 <- Heatmap(single_pathway_best_icbp[,c(1,2,3,4)],
                cluster_rows = T,
                cluster_columns = T,
                column_dend_reorder = c(1,4,400,1),
                show_row_names = F,
                show_column_names = T,
                split=factor(kmeans.4.clusters$KMeans.Clusters,
                             levels=c("Survival/HER2 high",
                                      "Survival/HER2 low",
                                      "Growth/BAD high",
                                      "Growth/BAD low")),
                row_title_gp = gpar(fontsize =10),
                combined_name_fun = NULL,
                name="Scaled\nPathway\nActivity",
                top_annotation = topha,
                column_title = "ICBP",
                show_heatmap_legend = showLegends,
                heatmap_legend_param = list(color_bar = "continuous"))
  
  draw(ha_row_icbp2+h1+ha_row_icbp1, row_dend_side = "left", annotation_legend_side = "bottom")
}

#uncomment to create PDF version of 2d
# pdf("Fig2d.pdf", width=5.32)
# create_figure2_d_ICBP_kmeans(single_pathway_best_icbp, showLegends = F)
# dev.off()

create_figure2_d_ICBP_kmeans(single_pathway_best_icbp)
```

## TCGA, ER Positive Only
```{r echo=FALSE, warning=FALSE, message=FALSE, fig.width=7, fig.height=7}
create_figure2_a_TCGA_allpath(single_pathway_best_tcga, ersubset = "Positive")
```

## TCGA, ER Negative Only
```{r echo=FALSE, warning=FALSE, message=FALSE, fig.width=7, fig.height=7}
create_figure2_a_TCGA_allpath(single_pathway_best_tcga, ersubset="Negative")
```

## ICBP, ER Positive Only
```{r echo=FALSE, warning=FALSE, message=FALSE, fig.width=7, fig.height=7}
create_figure2_b_ICBP_allpath(single_pathway_best_icbp, ersubset = "Positive")
```

## ICBP, ER Negative Only
```{r echo=FALSE, warning=FALSE, message=FALSE, fig.width=7, fig.height=7}
create_figure2_b_ICBP_allpath(single_pathway_best_icbp, ersubset = "Negative")
```