---
title: "GFRN Paper: Linear Models of TCGA PCA"
author: "David Jenkins"
date: "Feb 2, 2016"
output:
  html_document:
    toc: true
    toc_float: true
    theme: "united"
---

```{r echo=FALSE, warning=FALSE, message=FALSE}
library(ggplot2)
library(gridExtra)
#install development version of ComplexHeatmap https://github.com/jokergoo/ComplexHeatmap
library(ComplexHeatmap)
library(data.table)
library(RColorBrewer)
library(cluster)
library(knitr)

#-------------------------------------------------------------------------------
#Input files (Modify These to Your System's Locations):
#-------------------------------------------------------------------------------
input_data_dir <- file.path("")
#the input should be scaled pathway prediction values, from AdditionalFile3
icbp_predictions_file <- file.path(input_data_dir,
                                   "optimized_single_pathway_icbp_scaled.txt")
#the input should be scaled pathway prediction values, from AdditionalFile3
tcga_predictions_file <- file.path(input_data_dir,
                                   "optimized_single_pathway_tcga_scaled.txt")
icbp_status_file <- file.path(input_data_dir,
                              "icbpstatus_v2.txt")
icbp_intrinsic_file <- file.path(input_data_dir,
                                 "intrinsic.txt")
tcga_status_rds_file <- file.path(input_data_dir,
                                  "tcga_er_pr_her2_formatted.rds")
tcga_intrinsic_file <- file.path(input_data_dir,
                                 "TCGA_single_pathway_best_phenotype_intrinsic.txt")
tcga_brca_tumor_gene_expression_file <- file.path(input_data_dir,
                                                  "PANCAN24_BRCA_1119_TPMlog2.txt")

#-------------------------------------------------------------------------------
#Prepare TCGA Input:
#-------------------------------------------------------------------------------
#input tcga pathway data
single_pathway_best_tcga <-read.table(tcga_predictions_file, stringsAsFactors=FALSE,
                                      header=1, row.names=1,sep='\t')
#IHC Subtypes TCGA
er_pr_her2_status2 <- readRDS(tcga_status_rds_file)
#Intrinsic Subtypes TCGA
tcgaintrinsic <- read.table(tcga_intrinsic_file, 
                            row.names = 1, header=T, sep="\t")
tcgaintrinsic <- tcgaintrinsic[rownames(single_pathway_best_tcga),12,drop=F]
tcgaintrinsic$PAM50 <- as.character(tcgaintrinsic$PAM50)
rownames(tcgaintrinsic) <- rownames(single_pathway_best_tcga)
tcgaintrinsic$PAM50[is.na(tcgaintrinsic$PAM50)] <- "Unavailable"
tcgaintrinsic <- cbind(er_pr_her2_status2, tcgaintrinsic)
single_pathway_best_tcga <- cbind(single_pathway_best_tcga, tcgaintrinsic)
rm(er_pr_her2_status2, tcgaintrinsic)

single_pathway_best_tcga_noNA <- single_pathway_best_tcga[single_pathway_best_tcga$ER.Status != "Indeterminate",]
single_pathway_best_tcga_noNA <- single_pathway_best_tcga_noNA[single_pathway_best_tcga_noNA$ER.Status != "Unavailable",]
single_pathway_best_tcga_noNA <- single_pathway_best_tcga_noNA[single_pathway_best_tcga_noNA$PR.Status != "Indeterminate",]
single_pathway_best_tcga_noNA <- single_pathway_best_tcga_noNA[single_pathway_best_tcga_noNA$PR.Status != "Unavailable",]
single_pathway_best_tcga_noNA <- single_pathway_best_tcga_noNA[single_pathway_best_tcga_noNA$HER2.Status != "Equivocal",]
single_pathway_best_tcga_noNA <- single_pathway_best_tcga_noNA[single_pathway_best_tcga_noNA$HER2.Status != "Indeterminate",]
single_pathway_best_tcga_noNA <- single_pathway_best_tcga_noNA[single_pathway_best_tcga_noNA$HER2.Status != "Unavailable",]
single_pathway_best_tcga_noNA <- single_pathway_best_tcga_noNA[single_pathway_best_tcga_noNA$PAM50 != "Unavailable",]
single_pathway_best_tcga_noNA$ER.Status <- factor(single_pathway_best_tcga_noNA$ER.Status)
single_pathway_best_tcga_noNA$PR.Status <- factor(single_pathway_best_tcga_noNA$PR.Status)
single_pathway_best_tcga_noNA$HER2.Status <- factor(single_pathway_best_tcga_noNA$HER2.Status)
single_pathway_best_tcga_noNA$PAM50 <- factor(single_pathway_best_tcga_noNA$PAM50)

# Breast Cancer TCGA gene expression data
tcga_expression_full <-data.frame(fread(tcga_brca_tumor_gene_expression_file), check.names=F,row.names=1)
# Filter for low varying genes
#dim(test) #23368
tcga_expression <-tcga_expression_full[apply(tcga_expression_full[,1:ncol(tcga_expression_full)]==0,1,mean) < 0.85,]
#dim(test_f) #21307
```

```{r echo=FALSE, warning=FALSE, message=FALSE}
run_all_lms <- function(indata){
  a <- vector()
  a <- append(a, list(lm(PC1 ~ kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC1 ~ phenotype, data=indata)))
  a <- append(a, list(lm(PC1 ~ phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC1 ~ PAM50, data=indata)))
  a <- append(a, list(lm(PC1 ~ PAM50 + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC1 ~ PAM50 + phenotype, data=indata)))
  a <- append(a, list(lm(PC1 ~ PAM50 + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC1 ~ HER2.Status, data=indata)))
  a <- append(a, list(lm(PC1 ~ HER2.Status + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC1 ~ HER2.Status + phenotype, data=indata)))
  a <- append(a, list(lm(PC1 ~ HER2.Status + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC1 ~ HER2.Status + PAM50, data=indata)))
  a <- append(a, list(lm(PC1 ~ HER2.Status + PAM50 + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC1 ~ HER2.Status + PAM50 + phenotype, data=indata)))
  a <- append(a, list(lm(PC1 ~ HER2.Status + PAM50 + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC1 ~ PR.Status, data=indata)))
  a <- append(a, list(lm(PC1 ~ PR.Status + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC1 ~ PR.Status + phenotype, data=indata)))
  a <- append(a, list(lm(PC1 ~ PR.Status + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC1 ~ PR.Status + PAM50, data=indata)))
  a <- append(a, list(lm(PC1 ~ PR.Status + PAM50 + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC1 ~ PR.Status + PAM50 + phenotype, data=indata)))
  a <- append(a, list(lm(PC1 ~ PR.Status + PAM50 + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC1 ~ PR.Status + HER2.Status, data=indata)))
  a <- append(a, list(lm(PC1 ~ PR.Status + HER2.Status + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC1 ~ PR.Status + HER2.Status + phenotype, data=indata)))
  a <- append(a, list(lm(PC1 ~ PR.Status + HER2.Status + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC1 ~ PR.Status + HER2.Status + PAM50, data=indata)))
  a <- append(a, list(lm(PC1 ~ PR.Status + HER2.Status + PAM50 + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC1 ~ PR.Status + HER2.Status + PAM50 + phenotype, data=indata)))
  a <- append(a, list(lm(PC1 ~ PR.Status + HER2.Status + PAM50 + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC1 ~ ER.Status, data=indata)))
  a <- append(a, list(lm(PC1 ~ ER.Status + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC1 ~ ER.Status + phenotype, data=indata)))
  a <- append(a, list(lm(PC1 ~ ER.Status + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC1 ~ ER.Status + PAM50, data=indata)))
  a <- append(a, list(lm(PC1 ~ ER.Status + PAM50 + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC1 ~ ER.Status + PAM50 + phenotype, data=indata)))
  a <- append(a, list(lm(PC1 ~ ER.Status + PAM50 + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC1 ~ ER.Status + HER2.Status, data=indata)))
  a <- append(a, list(lm(PC1 ~ ER.Status + HER2.Status + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC1 ~ ER.Status + HER2.Status + phenotype, data=indata)))
  a <- append(a, list(lm(PC1 ~ ER.Status + HER2.Status + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC1 ~ ER.Status + HER2.Status + PAM50, data=indata)))
  a <- append(a, list(lm(PC1 ~ ER.Status + HER2.Status + PAM50 + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC1 ~ ER.Status + HER2.Status + PAM50 + phenotype, data=indata)))
  a <- append(a, list(lm(PC1 ~ ER.Status + HER2.Status + PAM50 + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC1 ~ ER.Status + PR.Status, data=indata)))
  a <- append(a, list(lm(PC1 ~ ER.Status + PR.Status + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC1 ~ ER.Status + PR.Status + phenotype, data=indata)))
  a <- append(a, list(lm(PC1 ~ ER.Status + PR.Status + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC1 ~ ER.Status + PR.Status + PAM50, data=indata)))
  a <- append(a, list(lm(PC1 ~ ER.Status + PR.Status + PAM50 + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC1 ~ ER.Status + PR.Status + PAM50 + phenotype, data=indata)))
  a <- append(a, list(lm(PC1 ~ ER.Status + PR.Status + PAM50 + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC1 ~ ER.Status + PR.Status + HER2.Status, data=indata)))
  a <- append(a, list(lm(PC1 ~ ER.Status + PR.Status + HER2.Status + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC1 ~ ER.Status + PR.Status + HER2.Status + phenotype, data=indata)))
  a <- append(a, list(lm(PC1 ~ ER.Status + PR.Status + HER2.Status + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC1 ~ ER.Status + PR.Status + HER2.Status + PAM50, data=indata)))
  a <- append(a, list(lm(PC1 ~ ER.Status + PR.Status + HER2.Status + PAM50 + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC1 ~ ER.Status + PR.Status + HER2.Status + PAM50 + phenotype, data=indata)))
  a <- append(a, list(lm(PC1 ~ ER.Status + PR.Status + HER2.Status + PAM50 + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC2 ~ kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC2 ~ phenotype, data=indata)))
  a <- append(a, list(lm(PC2 ~ phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC2 ~ PAM50, data=indata)))
  a <- append(a, list(lm(PC2 ~ PAM50 + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC2 ~ PAM50 + phenotype, data=indata)))
  a <- append(a, list(lm(PC2 ~ PAM50 + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC2 ~ HER2.Status, data=indata)))
  a <- append(a, list(lm(PC2 ~ HER2.Status + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC2 ~ HER2.Status + phenotype, data=indata)))
  a <- append(a, list(lm(PC2 ~ HER2.Status + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC2 ~ HER2.Status + PAM50, data=indata)))
  a <- append(a, list(lm(PC2 ~ HER2.Status + PAM50 + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC2 ~ HER2.Status + PAM50 + phenotype, data=indata)))
  a <- append(a, list(lm(PC2 ~ HER2.Status + PAM50 + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC2 ~ PR.Status, data=indata)))
  a <- append(a, list(lm(PC2 ~ PR.Status + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC2 ~ PR.Status + phenotype, data=indata)))
  a <- append(a, list(lm(PC2 ~ PR.Status + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC2 ~ PR.Status + PAM50, data=indata)))
  a <- append(a, list(lm(PC2 ~ PR.Status + PAM50 + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC2 ~ PR.Status + PAM50 + phenotype, data=indata)))
  a <- append(a, list(lm(PC2 ~ PR.Status + PAM50 + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC2 ~ PR.Status + HER2.Status, data=indata)))
  a <- append(a, list(lm(PC2 ~ PR.Status + HER2.Status + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC2 ~ PR.Status + HER2.Status + phenotype, data=indata)))
  a <- append(a, list(lm(PC2 ~ PR.Status + HER2.Status + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC2 ~ PR.Status + HER2.Status + PAM50, data=indata)))
  a <- append(a, list(lm(PC2 ~ PR.Status + HER2.Status + PAM50 + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC2 ~ PR.Status + HER2.Status + PAM50 + phenotype, data=indata)))
  a <- append(a, list(lm(PC2 ~ PR.Status + HER2.Status + PAM50 + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC2 ~ ER.Status, data=indata)))
  a <- append(a, list(lm(PC2 ~ ER.Status + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC2 ~ ER.Status + phenotype, data=indata)))
  a <- append(a, list(lm(PC2 ~ ER.Status + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC2 ~ ER.Status + PAM50, data=indata)))
  a <- append(a, list(lm(PC2 ~ ER.Status + PAM50 + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC2 ~ ER.Status + PAM50 + phenotype, data=indata)))
  a <- append(a, list(lm(PC2 ~ ER.Status + PAM50 + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC2 ~ ER.Status + HER2.Status, data=indata)))
  a <- append(a, list(lm(PC2 ~ ER.Status + HER2.Status + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC2 ~ ER.Status + HER2.Status + phenotype, data=indata)))
  a <- append(a, list(lm(PC2 ~ ER.Status + HER2.Status + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC2 ~ ER.Status + HER2.Status + PAM50, data=indata)))
  a <- append(a, list(lm(PC2 ~ ER.Status + HER2.Status + PAM50 + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC2 ~ ER.Status + HER2.Status + PAM50 + phenotype, data=indata)))
  a <- append(a, list(lm(PC2 ~ ER.Status + HER2.Status + PAM50 + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC2 ~ ER.Status + PR.Status, data=indata)))
  a <- append(a, list(lm(PC2 ~ ER.Status + PR.Status + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC2 ~ ER.Status + PR.Status + phenotype, data=indata)))
  a <- append(a, list(lm(PC2 ~ ER.Status + PR.Status + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC2 ~ ER.Status + PR.Status + PAM50, data=indata)))
  a <- append(a, list(lm(PC2 ~ ER.Status + PR.Status + PAM50 + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC2 ~ ER.Status + PR.Status + PAM50 + phenotype, data=indata)))
  a <- append(a, list(lm(PC2 ~ ER.Status + PR.Status + PAM50 + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC2 ~ ER.Status + PR.Status + HER2.Status, data=indata)))
  a <- append(a, list(lm(PC2 ~ ER.Status + PR.Status + HER2.Status + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC2 ~ ER.Status + PR.Status + HER2.Status + phenotype, data=indata)))
  a <- append(a, list(lm(PC2 ~ ER.Status + PR.Status + HER2.Status + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC2 ~ ER.Status + PR.Status + HER2.Status + PAM50, data=indata)))
  a <- append(a, list(lm(PC2 ~ ER.Status + PR.Status + HER2.Status + PAM50 + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC2 ~ ER.Status + PR.Status + HER2.Status + PAM50 + phenotype, data=indata)))
  a <- append(a, list(lm(PC2 ~ ER.Status + PR.Status + HER2.Status + PAM50 + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC3 ~ kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC3 ~ phenotype, data=indata)))
  a <- append(a, list(lm(PC3 ~ phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC3 ~ PAM50, data=indata)))
  a <- append(a, list(lm(PC3 ~ PAM50 + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC3 ~ PAM50 + phenotype, data=indata)))
  a <- append(a, list(lm(PC3 ~ PAM50 + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC3 ~ HER2.Status, data=indata)))
  a <- append(a, list(lm(PC3 ~ HER2.Status + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC3 ~ HER2.Status + phenotype, data=indata)))
  a <- append(a, list(lm(PC3 ~ HER2.Status + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC3 ~ HER2.Status + PAM50, data=indata)))
  a <- append(a, list(lm(PC3 ~ HER2.Status + PAM50 + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC3 ~ HER2.Status + PAM50 + phenotype, data=indata)))
  a <- append(a, list(lm(PC3 ~ HER2.Status + PAM50 + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC3 ~ PR.Status, data=indata)))
  a <- append(a, list(lm(PC3 ~ PR.Status + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC3 ~ PR.Status + phenotype, data=indata)))
  a <- append(a, list(lm(PC3 ~ PR.Status + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC3 ~ PR.Status + PAM50, data=indata)))
  a <- append(a, list(lm(PC3 ~ PR.Status + PAM50 + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC3 ~ PR.Status + PAM50 + phenotype, data=indata)))
  a <- append(a, list(lm(PC3 ~ PR.Status + PAM50 + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC3 ~ PR.Status + HER2.Status, data=indata)))
  a <- append(a, list(lm(PC3 ~ PR.Status + HER2.Status + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC3 ~ PR.Status + HER2.Status + phenotype, data=indata)))
  a <- append(a, list(lm(PC3 ~ PR.Status + HER2.Status + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC3 ~ PR.Status + HER2.Status + PAM50, data=indata)))
  a <- append(a, list(lm(PC3 ~ PR.Status + HER2.Status + PAM50 + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC3 ~ PR.Status + HER2.Status + PAM50 + phenotype, data=indata)))
  a <- append(a, list(lm(PC3 ~ PR.Status + HER2.Status + PAM50 + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC3 ~ ER.Status, data=indata)))
  a <- append(a, list(lm(PC3 ~ ER.Status + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC3 ~ ER.Status + phenotype, data=indata)))
  a <- append(a, list(lm(PC3 ~ ER.Status + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC3 ~ ER.Status + PAM50, data=indata)))
  a <- append(a, list(lm(PC3 ~ ER.Status + PAM50 + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC3 ~ ER.Status + PAM50 + phenotype, data=indata)))
  a <- append(a, list(lm(PC3 ~ ER.Status + PAM50 + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC3 ~ ER.Status + HER2.Status, data=indata)))
  a <- append(a, list(lm(PC3 ~ ER.Status + HER2.Status + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC3 ~ ER.Status + HER2.Status + phenotype, data=indata)))
  a <- append(a, list(lm(PC3 ~ ER.Status + HER2.Status + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC3 ~ ER.Status + HER2.Status + PAM50, data=indata)))
  a <- append(a, list(lm(PC3 ~ ER.Status + HER2.Status + PAM50 + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC3 ~ ER.Status + HER2.Status + PAM50 + phenotype, data=indata)))
  a <- append(a, list(lm(PC3 ~ ER.Status + HER2.Status + PAM50 + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC3 ~ ER.Status + PR.Status, data=indata)))
  a <- append(a, list(lm(PC3 ~ ER.Status + PR.Status + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC3 ~ ER.Status + PR.Status + phenotype, data=indata)))
  a <- append(a, list(lm(PC3 ~ ER.Status + PR.Status + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC3 ~ ER.Status + PR.Status + PAM50, data=indata)))
  a <- append(a, list(lm(PC3 ~ ER.Status + PR.Status + PAM50 + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC3 ~ ER.Status + PR.Status + PAM50 + phenotype, data=indata)))
  a <- append(a, list(lm(PC3 ~ ER.Status + PR.Status + PAM50 + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC3 ~ ER.Status + PR.Status + HER2.Status, data=indata)))
  a <- append(a, list(lm(PC3 ~ ER.Status + PR.Status + HER2.Status + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC3 ~ ER.Status + PR.Status + HER2.Status + phenotype, data=indata)))
  a <- append(a, list(lm(PC3 ~ ER.Status + PR.Status + HER2.Status + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC3 ~ ER.Status + PR.Status + HER2.Status + PAM50, data=indata)))
  a <- append(a, list(lm(PC3 ~ ER.Status + PR.Status + HER2.Status + PAM50 + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC3 ~ ER.Status + PR.Status + HER2.Status + PAM50 + phenotype, data=indata)))
  a <- append(a, list(lm(PC3 ~ ER.Status + PR.Status + HER2.Status + PAM50 + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC4 ~ kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC4 ~ phenotype, data=indata)))
  a <- append(a, list(lm(PC4 ~ phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC4 ~ PAM50, data=indata)))
  a <- append(a, list(lm(PC4 ~ PAM50 + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC4 ~ PAM50 + phenotype, data=indata)))
  a <- append(a, list(lm(PC4 ~ PAM50 + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC4 ~ HER2.Status, data=indata)))
  a <- append(a, list(lm(PC4 ~ HER2.Status + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC4 ~ HER2.Status + phenotype, data=indata)))
  a <- append(a, list(lm(PC4 ~ HER2.Status + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC4 ~ HER2.Status + PAM50, data=indata)))
  a <- append(a, list(lm(PC4 ~ HER2.Status + PAM50 + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC4 ~ HER2.Status + PAM50 + phenotype, data=indata)))
  a <- append(a, list(lm(PC4 ~ HER2.Status + PAM50 + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC4 ~ PR.Status, data=indata)))
  a <- append(a, list(lm(PC4 ~ PR.Status + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC4 ~ PR.Status + phenotype, data=indata)))
  a <- append(a, list(lm(PC4 ~ PR.Status + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC4 ~ PR.Status + PAM50, data=indata)))
  a <- append(a, list(lm(PC4 ~ PR.Status + PAM50 + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC4 ~ PR.Status + PAM50 + phenotype, data=indata)))
  a <- append(a, list(lm(PC4 ~ PR.Status + PAM50 + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC4 ~ PR.Status + HER2.Status, data=indata)))
  a <- append(a, list(lm(PC4 ~ PR.Status + HER2.Status + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC4 ~ PR.Status + HER2.Status + phenotype, data=indata)))
  a <- append(a, list(lm(PC4 ~ PR.Status + HER2.Status + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC4 ~ PR.Status + HER2.Status + PAM50, data=indata)))
  a <- append(a, list(lm(PC4 ~ PR.Status + HER2.Status + PAM50 + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC4 ~ PR.Status + HER2.Status + PAM50 + phenotype, data=indata)))
  a <- append(a, list(lm(PC4 ~ PR.Status + HER2.Status + PAM50 + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC4 ~ ER.Status, data=indata)))
  a <- append(a, list(lm(PC4 ~ ER.Status + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC4 ~ ER.Status + phenotype, data=indata)))
  a <- append(a, list(lm(PC4 ~ ER.Status + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC4 ~ ER.Status + PAM50, data=indata)))
  a <- append(a, list(lm(PC4 ~ ER.Status + PAM50 + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC4 ~ ER.Status + PAM50 + phenotype, data=indata)))
  a <- append(a, list(lm(PC4 ~ ER.Status + PAM50 + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC4 ~ ER.Status + HER2.Status, data=indata)))
  a <- append(a, list(lm(PC4 ~ ER.Status + HER2.Status + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC4 ~ ER.Status + HER2.Status + phenotype, data=indata)))
  a <- append(a, list(lm(PC4 ~ ER.Status + HER2.Status + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC4 ~ ER.Status + HER2.Status + PAM50, data=indata)))
  a <- append(a, list(lm(PC4 ~ ER.Status + HER2.Status + PAM50 + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC4 ~ ER.Status + HER2.Status + PAM50 + phenotype, data=indata)))
  a <- append(a, list(lm(PC4 ~ ER.Status + HER2.Status + PAM50 + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC4 ~ ER.Status + PR.Status, data=indata)))
  a <- append(a, list(lm(PC4 ~ ER.Status + PR.Status + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC4 ~ ER.Status + PR.Status + phenotype, data=indata)))
  a <- append(a, list(lm(PC4 ~ ER.Status + PR.Status + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC4 ~ ER.Status + PR.Status + PAM50, data=indata)))
  a <- append(a, list(lm(PC4 ~ ER.Status + PR.Status + PAM50 + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC4 ~ ER.Status + PR.Status + PAM50 + phenotype, data=indata)))
  a <- append(a, list(lm(PC4 ~ ER.Status + PR.Status + PAM50 + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC4 ~ ER.Status + PR.Status + HER2.Status, data=indata)))
  a <- append(a, list(lm(PC4 ~ ER.Status + PR.Status + HER2.Status + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC4 ~ ER.Status + PR.Status + HER2.Status + phenotype, data=indata)))
  a <- append(a, list(lm(PC4 ~ ER.Status + PR.Status + HER2.Status + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC4 ~ ER.Status + PR.Status + HER2.Status + PAM50, data=indata)))
  a <- append(a, list(lm(PC4 ~ ER.Status + PR.Status + HER2.Status + PAM50 + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC4 ~ ER.Status + PR.Status + HER2.Status + PAM50 + phenotype, data=indata)))
  a <- append(a, list(lm(PC4 ~ ER.Status + PR.Status + HER2.Status + PAM50 + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC5 ~ kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC5 ~ phenotype, data=indata)))
  a <- append(a, list(lm(PC5 ~ phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC5 ~ PAM50, data=indata)))
  a <- append(a, list(lm(PC5 ~ PAM50 + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC5 ~ PAM50 + phenotype, data=indata)))
  a <- append(a, list(lm(PC5 ~ PAM50 + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC5 ~ HER2.Status, data=indata)))
  a <- append(a, list(lm(PC5 ~ HER2.Status + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC5 ~ HER2.Status + phenotype, data=indata)))
  a <- append(a, list(lm(PC5 ~ HER2.Status + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC5 ~ HER2.Status + PAM50, data=indata)))
  a <- append(a, list(lm(PC5 ~ HER2.Status + PAM50 + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC5 ~ HER2.Status + PAM50 + phenotype, data=indata)))
  a <- append(a, list(lm(PC5 ~ HER2.Status + PAM50 + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC5 ~ PR.Status, data=indata)))
  a <- append(a, list(lm(PC5 ~ PR.Status + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC5 ~ PR.Status + phenotype, data=indata)))
  a <- append(a, list(lm(PC5 ~ PR.Status + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC5 ~ PR.Status + PAM50, data=indata)))
  a <- append(a, list(lm(PC5 ~ PR.Status + PAM50 + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC5 ~ PR.Status + PAM50 + phenotype, data=indata)))
  a <- append(a, list(lm(PC5 ~ PR.Status + PAM50 + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC5 ~ PR.Status + HER2.Status, data=indata)))
  a <- append(a, list(lm(PC5 ~ PR.Status + HER2.Status + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC5 ~ PR.Status + HER2.Status + phenotype, data=indata)))
  a <- append(a, list(lm(PC5 ~ PR.Status + HER2.Status + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC5 ~ PR.Status + HER2.Status + PAM50, data=indata)))
  a <- append(a, list(lm(PC5 ~ PR.Status + HER2.Status + PAM50 + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC5 ~ PR.Status + HER2.Status + PAM50 + phenotype, data=indata)))
  a <- append(a, list(lm(PC5 ~ PR.Status + HER2.Status + PAM50 + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC5 ~ ER.Status, data=indata)))
  a <- append(a, list(lm(PC5 ~ ER.Status + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC5 ~ ER.Status + phenotype, data=indata)))
  a <- append(a, list(lm(PC5 ~ ER.Status + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC5 ~ ER.Status + PAM50, data=indata)))
  a <- append(a, list(lm(PC5 ~ ER.Status + PAM50 + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC5 ~ ER.Status + PAM50 + phenotype, data=indata)))
  a <- append(a, list(lm(PC5 ~ ER.Status + PAM50 + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC5 ~ ER.Status + HER2.Status, data=indata)))
  a <- append(a, list(lm(PC5 ~ ER.Status + HER2.Status + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC5 ~ ER.Status + HER2.Status + phenotype, data=indata)))
  a <- append(a, list(lm(PC5 ~ ER.Status + HER2.Status + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC5 ~ ER.Status + HER2.Status + PAM50, data=indata)))
  a <- append(a, list(lm(PC5 ~ ER.Status + HER2.Status + PAM50 + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC5 ~ ER.Status + HER2.Status + PAM50 + phenotype, data=indata)))
  a <- append(a, list(lm(PC5 ~ ER.Status + HER2.Status + PAM50 + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC5 ~ ER.Status + PR.Status, data=indata)))
  a <- append(a, list(lm(PC5 ~ ER.Status + PR.Status + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC5 ~ ER.Status + PR.Status + phenotype, data=indata)))
  a <- append(a, list(lm(PC5 ~ ER.Status + PR.Status + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC5 ~ ER.Status + PR.Status + PAM50, data=indata)))
  a <- append(a, list(lm(PC5 ~ ER.Status + PR.Status + PAM50 + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC5 ~ ER.Status + PR.Status + PAM50 + phenotype, data=indata)))
  a <- append(a, list(lm(PC5 ~ ER.Status + PR.Status + PAM50 + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC5 ~ ER.Status + PR.Status + HER2.Status, data=indata)))
  a <- append(a, list(lm(PC5 ~ ER.Status + PR.Status + HER2.Status + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC5 ~ ER.Status + PR.Status + HER2.Status + phenotype, data=indata)))
  a <- append(a, list(lm(PC5 ~ ER.Status + PR.Status + HER2.Status + phenotype + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC5 ~ ER.Status + PR.Status + HER2.Status + PAM50, data=indata)))
  a <- append(a, list(lm(PC5 ~ ER.Status + PR.Status + HER2.Status + PAM50 + kmeans.cluster, data=indata)))
  a <- append(a, list(lm(PC5 ~ ER.Status + PR.Status + HER2.Status + PAM50 + phenotype, data=indata)))
  a <- append(a, list(lm(PC5 ~ ER.Status + PR.Status + HER2.Status + PAM50 + phenotype + kmeans.cluster, data=indata)))
  return(a)
}

pca_mat <- prcomp(t(tcga_expression), center=T,scale=T)
cum_tcga<-cumsum((pca_mat$sdev)^2) / sum(pca_mat$sdev^2) #calculates cumulative proportiono of variances
```

# PCA lms

## PCA Before Removing "Unknown" samples in any category, n=355

```{r echo=FALSE, warning=FALSE, message=FALSE}
# Run PCA analysis in TCGA
firstfive_TCGA <- data.frame(pca_mat$x[,1:5])
firstfive_TCGA <- firstfive_TCGA[rownames(single_pathway_best_tcga_noNA),]
firstfive_TCGA <- cbind(firstfive_TCGA, single_pathway_best_tcga_noNA[,8:13])
unknown_remove_all <- run_all_lms(firstfive_TCGA)
unknown_remove_all_result <- data.frame(R2=unlist(lapply(unknown_remove_all, function(x) summary(x)$r.squared)), p=unlist(lapply(unknown_remove_all, function(x) summary(x)$r.squared)))

result_df_ER <- data.frame(
PC=c(1:5),

ER=c(unknown_remove_all_result[32,1], #ER PC1
  unknown_remove_all_result[95,1], #ER PC2
  unknown_remove_all_result[158,1], #ER PC3
  unknown_remove_all_result[221,1], #ER PC4
  unknown_remove_all_result[284,1]), #ER PC5

ER.kmeans=c(unknown_remove_all_result[33,1], #ER + kmeans PC1
  unknown_remove_all_result[96,1], #ER + kmeans PC2
  unknown_remove_all_result[159,1], #ER + kmeans PC3
  unknown_remove_all_result[222,1], #ER + kmeans PC4
  unknown_remove_all_result[285,1]), #ER + kmeans PC5

ER.kmeans.pval=c(anova(unknown_remove_all[[32]], unknown_remove_all[[33]])[6][2,1], #ER + kmeans PC1
  anova(unknown_remove_all[[95]], unknown_remove_all[[96]])[6][2,1], #ER + kmeans PC2
  anova(unknown_remove_all[[158]], unknown_remove_all[[159]])[6][2,1], #ER + kmeans PC3
  anova(unknown_remove_all[[221]], unknown_remove_all[[222]])[6][2,1], #ER + kmeans PC4
  anova(unknown_remove_all[[284]], unknown_remove_all[[285]])[6][2,1]), #ER + kmeans PC5

ER.PAM50=c(unknown_remove_all_result[33+3,1], #ER + PAM50 PC1
  unknown_remove_all_result[96+3,1], #ER + PAM50 PC2
  unknown_remove_all_result[159+3,1], #ER + PAM50 PC3
  unknown_remove_all_result[222+3,1], #ER + PAM50 PC4
  unknown_remove_all_result[285+3,1]), #ER + PAM50 PC5

ER.PAM50.pval=c(anova(unknown_remove_all[[32]], unknown_remove_all[[33+3]])[6][2,1], #ER + PAM50 PC1
  anova(unknown_remove_all[[95]], unknown_remove_all[[96+3]])[6][2,1], #ER + PAM50 PC2
  anova(unknown_remove_all[[158]], unknown_remove_all[[159+3]])[6][2,1], #ER + PAM50 PC3
  anova(unknown_remove_all[[221]], unknown_remove_all[[222+3]])[6][2,1], #ER + PAM50 PC4
  anova(unknown_remove_all[[284]], unknown_remove_all[[285+3]])[6][2,1]), #ER + PAM50 PC5

ER.phenotype=c(unknown_remove_all_result[33+1,1], #ER + GFRN Pheno PC1
  unknown_remove_all_result[96+1,1], #ER + GFRN Pheno PC2
  unknown_remove_all_result[159+1,1], #ER + GFRN Pheno PC3
  unknown_remove_all_result[222+1,1], #ER + GFRN Pheno PC4
  unknown_remove_all_result[285+1,1]), #ER + GFRN Pheno PC5

ER.phenotype.pval=c(anova(unknown_remove_all[[32]], unknown_remove_all[[33+1]])[6][2,1], #ER + GFRN Pheno PC1
  anova(unknown_remove_all[[95]], unknown_remove_all[[96+1]])[6][2,1], #ER + GFRN Pheno PC2
  anova(unknown_remove_all[[158]], unknown_remove_all[[159+1]])[6][2,1], #ER + GFRN Pheno PC3
  anova(unknown_remove_all[[221]], unknown_remove_all[[222+1]])[6][2,1], #ER + GFRN Pheno PC4
  anova(unknown_remove_all[[284]], unknown_remove_all[[285+1]])[6][2,1]), #ER + GFRN Pheno PC5

ER.kmeans.PAM50.pval=c(anova(unknown_remove_all[[33]], unknown_remove_all[[33+3]])[6][2,1],
  anova(unknown_remove_all[[96]], unknown_remove_all[[96+3]])[6][2,1],
  anova(unknown_remove_all[[159]], unknown_remove_all[[159+3]])[6][2,1],
  anova(unknown_remove_all[[222]], unknown_remove_all[[222+3]])[6][2,1],
  anova(unknown_remove_all[[285]], unknown_remove_all[[285+3]])[6][2,1])
)

result_df_PR <- data.frame(
PC=c(1:5),

PR=c(unknown_remove_all_result[16,1], #PR PC1
  unknown_remove_all_result[79,1], #PR PC2
  unknown_remove_all_result[142,1], #PR PC3
  unknown_remove_all_result[205,1], #PR PC4
  unknown_remove_all_result[268,1]), #PR PC5

PR.kmeans=c(unknown_remove_all_result[17,1], #PR + kmeans PC1
  unknown_remove_all_result[80,1], #PR + kmeans PC2
  unknown_remove_all_result[143,1], #PR + kmeans PC3
  unknown_remove_all_result[206,1], #PR + kmeans PC4
  unknown_remove_all_result[269,1]), #PR + kmeans PC5

PR.kmeans.pval=c(anova(unknown_remove_all[[16]], unknown_remove_all[[17]])[6][2,1], #PR + kmeans PC1
  anova(unknown_remove_all[[79]], unknown_remove_all[[80]])[6][2,1], #PR + kmeans PC2
  anova(unknown_remove_all[[142]], unknown_remove_all[[143]])[6][2,1], #PR + kmeans PC3
  anova(unknown_remove_all[[205]], unknown_remove_all[[206]])[6][2,1], #PR + kmeans PC4
  anova(unknown_remove_all[[268]], unknown_remove_all[[269]])[6][2,1]), #PR + kmeans PC5

PR.PAM50=c(unknown_remove_all_result[17+3,1], #PR + PAM50 PC1
  unknown_remove_all_result[80+3,1], #PR + PAM50 PC2
  unknown_remove_all_result[143+3,1], #PR + PAM50 PC3
  unknown_remove_all_result[206+3,1], #PR + PAM50 PC4
  unknown_remove_all_result[269+3,1]), #PR + PAM50 PC5

PR.PAM50.pval=c(anova(unknown_remove_all[[16]], unknown_remove_all[[17+3]])[6][2,1], #PR + PAM50 PC1
  anova(unknown_remove_all[[79]], unknown_remove_all[[80+3]])[6][2,1], #PR + PAM50 PC2
  anova(unknown_remove_all[[142]], unknown_remove_all[[143+3]])[6][2,1], #PR + PAM50 PC3
  anova(unknown_remove_all[[205]], unknown_remove_all[[206+3]])[6][2,1], #PR + PAM50 PC4
  anova(unknown_remove_all[[268]], unknown_remove_all[[269+3]])[6][2,1]), #PR + PAM50 PC5


PR.phenotype=c(unknown_remove_all_result[17+1,1], #PR + GFRN Pheno PC1
  unknown_remove_all_result[80+1,1], #PR + GFRN Pheno PC2
  unknown_remove_all_result[143+1,1], #PR + GFRN Pheno PC3
  unknown_remove_all_result[206+1,1], #PR + GFRN Pheno PC4
  unknown_remove_all_result[269+1,1]), #PR + GFRN Pheno PC5

PR.phenotype.pval=c(anova(unknown_remove_all[[16]], unknown_remove_all[[17+1]])[6][2,1], #PR + GFRN Pheno PC1
  anova(unknown_remove_all[[79]], unknown_remove_all[[80+1]])[6][2,1], #PR + GFRN Pheno PC2
  anova(unknown_remove_all[[142]], unknown_remove_all[[143+1]])[6][2,1], #PR + GFRN Pheno PC3
  anova(unknown_remove_all[[205]], unknown_remove_all[[206+1]])[6][2,1], #PR + GFRN Pheno PC4
  anova(unknown_remove_all[[268]], unknown_remove_all[[269+1]])[6][2,1]), #PR + GFRN Pheno PC5

PR.kmeans.PAM50.pval=c(anova(unknown_remove_all[[17]], unknown_remove_all[[17+3]])[6][2,1], #PR + PAM50 PC1
  anova(unknown_remove_all[[80]], unknown_remove_all[[80+3]])[6][2,1], #PR + PAM50 PC2
  anova(unknown_remove_all[[143]], unknown_remove_all[[143+3]])[6][2,1], #PR + PAM50 PC3
  anova(unknown_remove_all[[206]], unknown_remove_all[[206+3]])[6][2,1],
  anova(unknown_remove_all[[269]], unknown_remove_all[[269+3]])[6][2,1])
)

result_df_HER2 <- data.frame(
PC=c(1:5),

HER2=c(unknown_remove_all_result[8,1], #HER2 PC1
  unknown_remove_all_result[71,1], #HER2 PC2
  unknown_remove_all_result[134,1], #HER2 PC3
  unknown_remove_all_result[197,1], #HER2 PC4
  unknown_remove_all_result[260,1]), #HER2 PC5

HER2.kmeans=c(unknown_remove_all_result[9,1], #HER2 + kmeans PC1
  unknown_remove_all_result[72,1], #HER2 + kmeans PC2
  unknown_remove_all_result[135,1], #HER2 + kmeans PC3
  unknown_remove_all_result[198,1], #HER2 + kmeans PC4
  unknown_remove_all_result[261,1]), #HER2 + kmeans PC5

HER2.kmeans.pval=c(anova(unknown_remove_all[[8]], unknown_remove_all[[9]])[6][2,1], #HER2 + kmeans PC1
  anova(unknown_remove_all[[71]], unknown_remove_all[[72]])[6][2,1], #HER2 + kmeans PC2
  anova(unknown_remove_all[[134]], unknown_remove_all[[135]])[6][2,1], #HER2 + kmeans PC3
  anova(unknown_remove_all[[197]], unknown_remove_all[[198]])[6][2,1], #HER2 + kmeans PC4
  anova(unknown_remove_all[[260]], unknown_remove_all[[261]])[6][2,1]), #HER2 + kmeans PC5

HER2.PAM50=c(unknown_remove_all_result[9+3,1], #HER2 + PAM50 PC1
  unknown_remove_all_result[72+3,1], #HER2 + PAM50 PC2
  unknown_remove_all_result[135+3,1], #HER2 + PAM50 PC3
  unknown_remove_all_result[198+3,1], #HER2 + PAM50 PC4
  unknown_remove_all_result[261+3,1]), #HER2 + PAM50 PC5

HER2.PAM50.pval=c(anova(unknown_remove_all[[8]], unknown_remove_all[[9+3]])[6][2,1], #HER2 + PAM50 PC1
  anova(unknown_remove_all[[71]], unknown_remove_all[[72+3]])[6][2,1], #HER2 + PAM50 PC2
  anova(unknown_remove_all[[134]], unknown_remove_all[[135+3]])[6][2,1], #HER2 + PAM50 PC3
  anova(unknown_remove_all[[197]], unknown_remove_all[[198+3]])[6][2,1], #HER2 + PAM50 PC4
  anova(unknown_remove_all[[260]], unknown_remove_all[[261+3]])[6][2,1]), #HER2 + PAM50 PC5

HER2.phenotype=c(unknown_remove_all_result[9+1,1], #HER2 + GFRN Pheno PC1
  unknown_remove_all_result[72+1,1], #HER2 + GFRN Pheno PC2
  unknown_remove_all_result[135+1,1], #HER2 + GFRN Pheno PC3
  unknown_remove_all_result[198+1,1], #HER2 + GFRN Pheno PC4
  unknown_remove_all_result[261+1,1]), #HER2 + GFRN Pheno PC5

HER2.phenotype.pval=c(anova(unknown_remove_all[[8]], unknown_remove_all[[9+1]])[6][2,1], #HER2 + GFRN Pheno PC1
  anova(unknown_remove_all[[71]], unknown_remove_all[[72+1]])[6][2,1], #HER2 + GFRN Pheno PC2
  anova(unknown_remove_all[[134]], unknown_remove_all[[135+1]])[6][2,1], #HER2 + GFRN Pheno PC3
  anova(unknown_remove_all[[197]], unknown_remove_all[[198+1]])[6][2,1], #HER2 + GFRN Pheno PC4
  anova(unknown_remove_all[[260]], unknown_remove_all[[261+1]])[6][2,1]), #HER2 + GFRN Pheno PC5

HER2.kmeans.PAM50.pval=c(anova(unknown_remove_all[[9]], unknown_remove_all[[9+3]])[6][2,1],
  anova(unknown_remove_all[[72]], unknown_remove_all[[72+3]])[6][2,1],
  anova(unknown_remove_all[[135]], unknown_remove_all[[135+3]])[6][2,1],
  anova(unknown_remove_all[[198]], unknown_remove_all[[198+3]])[6][2,1],
  anova(unknown_remove_all[[261]], unknown_remove_all[[261+3]])[6][2,1])
)

result_df_all3 <- data.frame(
PC=c(1:5),

ER.PR.HER2=c(unknown_remove_all_result[56,1], #ER/PR/HER2 PC1
  unknown_remove_all_result[119,1], #ER/PR/HER2 PC2
  unknown_remove_all_result[182,1], #ER/PR/HER2 PC3
  unknown_remove_all_result[245,1], #ER/PR/HER2 PC4
  unknown_remove_all_result[308,1]), #ER/PR/HER2 PC5

ER.PR.HER2.kmeans=c(unknown_remove_all_result[57,1], #ER/PR/HER2 + kmeans PC1
  unknown_remove_all_result[120,1], #ER/PR/HER2 + kmeans PC2
  unknown_remove_all_result[183,1], #ER/PR/HER2 + kmeans PC3
  unknown_remove_all_result[246,1], #ER/PR/HER2 + kmeans PC4
  unknown_remove_all_result[309,1]), #ER/PR/HER2 + kmeans PC5

ER.PR.HER2.kmeans.pval=c(anova(unknown_remove_all[[56]], unknown_remove_all[[57]])[6][2,1], #ER.PR.HER2 + kmeans PC1
  anova(unknown_remove_all[[119]], unknown_remove_all[[120]])[6][2,1], #ER.PR.HER2 + kmeans PC2
  anova(unknown_remove_all[[182]], unknown_remove_all[[183]])[6][2,1], #ER.PR.HER2 + kmeans PC3
  anova(unknown_remove_all[[245]], unknown_remove_all[[246]])[6][2,1], #ER.PR.HER2 + kmeans PC4
  anova(unknown_remove_all[[308]], unknown_remove_all[[309]])[6][2,1]), #ER.PR.HER2 + kmeans PC5

ER.PR.HER2.PAM50=c(unknown_remove_all_result[57+3,1], #ER/PR/HER2 + PAM50 PC1
  unknown_remove_all_result[120+3,1], #ER/PR/HER2 + PAM50 PC2
  unknown_remove_all_result[183+3,1], #ER/PR/HER2 + PAM50 PC3
  unknown_remove_all_result[246+3,1], #ER/PR/HER2 + PAM50 PC4
  unknown_remove_all_result[309+3,1]), #ER/PR/HER2 + PAM50 PC5

ER.PR.HER2.PAM50.pval=c(anova(unknown_remove_all[[56]], unknown_remove_all[[57+3]])[6][2,1], #ER.PR.HER2 + PAM50 PC1
  anova(unknown_remove_all[[119]], unknown_remove_all[[120+3]])[6][2,1], #ER.PR.HER2 + PAM50 PC2
  anova(unknown_remove_all[[182]], unknown_remove_all[[183+3]])[6][2,1], #ER.PR.HER2 + PAM50 PC3
  anova(unknown_remove_all[[245]], unknown_remove_all[[246+3]])[6][2,1], #ER.PR.HER2 + PAM50 PC4
  anova(unknown_remove_all[[308]], unknown_remove_all[[309+3]])[6][2,1]), #ER.PR.HER2 + PAM50 PC5

ER.PR.HER2.phenotype=c(unknown_remove_all_result[57+1,1], #ER/PR/HER2 + GFRN Pheno PC1
  unknown_remove_all_result[120+1,1], #ER/PR/HER2 + GFRN Pheno PC2
  unknown_remove_all_result[183+1,1], #ER/PR/HER2 + GFRN Pheno PC3
  unknown_remove_all_result[246+1,1], #ER/PR/HER2 + GFRN Pheno PC4
  unknown_remove_all_result[309+1,1]), #ER/PR/HER2 + GFRN Pheno PC5

ER.PR.HER2.phenotype.pval=c(anova(unknown_remove_all[[56]], unknown_remove_all[[57+1]])[6][2,1], #ER.PR.HER2 + GFRN Pheno PC1
  anova(unknown_remove_all[[119]], unknown_remove_all[[120+1]])[6][2,1], #ER.PR.HER2 + GFRN Pheno PC2
  anova(unknown_remove_all[[182]], unknown_remove_all[[183+1]])[6][2,1], #ER.PR.HER2 + GFRN Pheno PC3
  anova(unknown_remove_all[[245]], unknown_remove_all[[246+1]])[6][2,1], #ER.PR.HER2 + GFRN Pheno PC4
  anova(unknown_remove_all[[308]], unknown_remove_all[[309+1]])[6][2,1]), #ER.PR.HER2 + GFRN Pheno PC5

ER.PR.HER2.kmeans.PAM50.pval=c(anova(unknown_remove_all[[57]], unknown_remove_all[[57+3]])[6][2,1],
  anova(unknown_remove_all[[120]], unknown_remove_all[[120+3]])[6][2,1],
  anova(unknown_remove_all[[183]], unknown_remove_all[[183+3]])[6][2,1],
  anova(unknown_remove_all[[246]], unknown_remove_all[[246+3]])[6][2,1],
  anova(unknown_remove_all[[309]], unknown_remove_all[[309+3]])[6][2,1])
)

result_df_misc <- data.frame(
PC=c(1:5),

kmeans=c(unknown_remove_all_result[1,1],
  unknown_remove_all_result[64,1],
  unknown_remove_all_result[127,1],
  unknown_remove_all_result[190,1],
  unknown_remove_all_result[253,1]),

PAM50=c(unknown_remove_all_result[1+3,1],
  unknown_remove_all_result[64+3,1],
  unknown_remove_all_result[127+3,1],
  unknown_remove_all_result[190+3,1],
  unknown_remove_all_result[253+3,1]),

kmeans.PAM50=c(unknown_remove_all_result[1+4,1],
  unknown_remove_all_result[64+4,1],
  unknown_remove_all_result[127+4,1],
  unknown_remove_all_result[190+4,1],
  unknown_remove_all_result[253+4,1]),

ER.PR.HER2.PAM50.kmeans=c(unknown_remove_all_result[1+60,1],
  unknown_remove_all_result[64+60,1],
  unknown_remove_all_result[127+60,1],
  unknown_remove_all_result[190+60,1],
  unknown_remove_all_result[253+60,1])
)

kable(result_df_ER)
kable(result_df_PR)
kable(result_df_HER2)
kable(result_df_all3)
kable(result_df_misc)
```
